# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSso < Formula
  desc "AWS account credentials using SSO"
  homepage "https://github.com/nanih98/aws-sso"
  version "0.0.1"
  license "Apache 2.0 license"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/naih98/aws-sso/releases/download/v0.0.1/aws-sso_0.0.1_Darwin_arm64.tar.gz"
      sha256 "5438e14f2aa236838b57003ec4a7a36801034bf9ada52aadd8b831f218811eb1"

      def install
        bin.install "aws-sso"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/naih98/aws-sso/releases/download/v0.0.1/aws-sso_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "8ce7ace8526f28c4906a11af73d60e8c3d2e2c9094a401196268578d50658772"

      def install
        bin.install "aws-sso"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/naih98/aws-sso/releases/download/v0.0.1/aws-sso_0.0.1_Linux_x86_64.tar.gz"
      sha256 "615c3bd677544d7b5147c9a7e3920edc276d54f3535d77f76750ee4a4e1328a2"

      def install
        bin.install "aws-sso"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/naih98/aws-sso/releases/download/v0.0.1/aws-sso_0.0.1_Linux_armv6.tar.gz"
      sha256 "321148d4b82d4632cc1e205a71495b6329e4a60f9fa6aff5537b780a9d58dbe8"

      def install
        bin.install "aws-sso"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/naih98/aws-sso/releases/download/v0.0.1/aws-sso_0.0.1_Linux_arm64.tar.gz"
      sha256 "fc5fca89633a49c4773252b3bbe778137c1f094ae878b4c2f523454fa550a957"

      def install
        bin.install "aws-sso"
      end
    end
  end
end
